import json

pop = {r['ticker']: r for r in json.load(open('.scan_scratch/research_population.json'))}

research = {
'BESI.AS': dict(strategy_type='TURNAROUND', alt=51, inst=50, align='CAUTIOUS', risk='REJECT',
    research_summary="Sharp sector-wide chip-bear-market pullback (EUR196-214->EUR176) despite record H1 revenue/AI demand and Buy consensus.",
    risk_reason="R:R fails hard floor (1.39<1.5), compounded by wide 9.91% stop and SHORT-BIAS sector headwind."),
'GOOG': dict(strategy_type='POSITION', alt=42, inst=55, align='CAUTIOUS', risk='CAUTION',
    research_summary="Antitrust win (ad-exchange breakup rejected) and Gemini momentum offset by capex overhang; weaker of the two Alphabet legs.",
    risk_reason="Correlated duplicate of GOOGL (must size as one position), R:R sits exactly at 1.5 floor, insider selling flag."),
'GOOGL': dict(strategy_type='POSITION', alt=61, inst=58, align='CAUTIOUS', risk='CAUTION',
    research_summary="Same antitrust win/Gemini momentum but cleanest alt-data read (MSPR bullish, low short interest) of the batch.",
    risk_reason="Best setup in batch but still AI-capex/rate-sensitive headwind; correlated with GOOG, R:R only marginal (1.52)."),
'TER': dict(strategy_type='TURNAROUND', alt=None, inst=50, align='CAUTIOUS', risk='REJECT',
    research_summary="Stock fell -13.3% in one session (Sept 14) to exactly the scan's entry level, on profit-taking amid the sector selloff.",
    risk_reason="R:R fails (1.47<1.5) and 11.66% stop exceeds every defined strategy risk band."),
'ALAB': dict(strategy_type='TURNAROUND', alt=None, inst=60, align='CAUTIOUS', risk='CAUTION',
    research_summary="Strong institutional backdrop (79.3% ownership, bullish Sept 4 options flow, +104% y/y revenue) but ~19% two-week pullback.",
    risk_reason="R:R acceptable (1.63) but 15.42% stop is widest in batch -- must cut size sharply; sector headwind."),

'MPWR': dict(strategy_type='TURNAROUND', alt=None, inst=42, align='CAUTIOUS', risk='CAUTION',
    research_summary="Oversold analog-power semi (RSI 24, -33% off highs) with fresh StoneX Buy initiation despite broad chip-sector weakness.",
    risk_reason="Reversal fights a confirmed Kindleberger Stage-4 sector headwind; no alt-data/institutional confirmation available."),
'FTNT': dict(strategy_type='POSITION', alt=45, inst=45, align='CAUTIOUS', risk='CAUTION',
    research_summary="Genuine Stage-2 uptrend with a real AI-security catalyst (Virtue AI acquisition closed Aug 17), but Wedbush downgraded to Neutral on 9/10.",
    risk_reason="R:R fails RISK.md minimum (1.46<1.5) and stop distance (9.24%) exceeds the 8% POSITION cap -- two independent RISK.md violations."),
'LRCX': dict(strategy_type='TURNAROUND', alt=None, inst=30, align='CONTRARIAN', risk='CAUTION',
    research_summary="Named (-6%) in the 2026-09-14 'AI pacing call' selloff that hit chip-equipment stocks -- the macro Stage-4 thesis materialized this week, not hypothetically.",
    risk_reason="Named in a dated, confirmed sector-selloff event; fundamentals (dividend hike, raised WFE guidance) strong but not enough alone to override."),
'ASML.AS': dict(strategy_type='TURNAROUND', alt=38, inst=32, align='CONTRARIAN', risk='REJECT',
    research_summary="Same 09-14 selloff (-5%) as LRCX; strong backlog/guidance but alt-data BEARISH and news sentiment falling.",
    risk_reason="Same company as ASML (US ADR) in this batch -- weaker leg on R:R (1.50 vs 2.05) and alt-data; correlated double-counting risk, reject in favor of the ADR."),
'ASML': dict(strategy_type='TURNAROUND', alt=48, inst=42, align='CAUTIOUS', risk='CAUTION',
    research_summary="Same underlying story as ASML.AS but cleaner profile: 85.7% analyst bull ratio, best R:R in batch (2.05), Bernstein sees +70% upside.",
    risk_reason="Elevated risk from the same dated sector selloff; preferred leg of the ASML pair but still needs 2-3 sessions of stabilization before APPROVE."),

'GEV': dict(strategy_type='TURNAROUND', alt=None, inst=50, align='CAUTIOUS', risk='CAUTION',
    research_summary="Wide analyst PT dispersion ($836-$1450), CFO transition, strong AI grid-demand tailwind vs. Fed hike/10Y>5% headwind.",
    risk_reason="R:R fails minimum (1.37<1.5), stop wide (9.04%), size to ~50% GOOD tier."),
'AIR.PA': dict(strategy_type='TURNAROUND', alt=43, inst=50, align='CAUTIOUS', risk='REJECT',
    research_summary="Deliveries +9% YTD, on track for 870-unit target, but target sits right at nearby resistance.",
    risk_reason="R:R FAIL (0.86, far below 1.5:1 RISK.md minimum), no mitigating room to target."),
'ENR.DE': dict(strategy_type='TURNAROUND', alt=46, inst=50, align='CAUTIOUS', risk='CAUTION',
    research_summary="EUR2B buyback + reaffirmed guidance, but stock fell -8.04% today coinciding exactly with Fed hike/10Y>5%.",
    risk_reason="R:R OK (1.60) but elevated volatility/macro-timing risk; wait for stabilization or reduce size."),
'SU.PA': dict(strategy_type='TURNAROUND', alt=46, inst=50, align='CAUTIOUS', risk='CAUTION',
    research_summary="Best-structured of the 4 Industrials names (R:R 1.82, highest volume confirm) but also fell -6.54% today, same macro cause.",
    risk_reason="R:R OK but same-day rate-shock volatility; reduce size ~75% pending confirmation."),
'CHRW': dict(strategy_type='SWING', alt=62, inst=52, align='CAUTIOUS', risk='CAUTION',
    research_summary="Solid Q2 (+19% rev), bullish insider MSPR, but $600M legal verdict overhang.",
    risk_reason="Live market_data.json shows RR collapsed to 0.05 intraday (Medium conviction, overbought RSI 76) -- major conflict with session's assigned figures; near-STAND DOWN."),

'WKL.AS': dict(strategy_type='POSITION', alt=43, inst=55, align='CAUTIOUS', risk='APPROVE',
    research_summary="Active EUR500M buyback + analyst PT raised EUR73->EUR87 on AI-moat re-rating.",
    risk_reason="Marginal R:R (1.72), stop within limits, only WARNING is the 3-way Industrials sector-cap conflict in this batch (resolved centrally -- only Industrials APPROVE)."),
'LUV': dict(strategy_type='SWING', alt=51, inst=45, align='CAUTIOUS', risk='REJECT',
    research_summary="Oil spiked to ~$108 Brent on Saudi pipeline outage -- direct jet-fuel cost headwind; analyst PT cuts (Barclays, UBS) despite held ratings.",
    risk_reason="R:R is 1.28, below the RISK.md 1.5:1 minimum -- hard rule violation."),
'TEP.PA': dict(strategy_type='SWING', alt=46, inst=35, align='CONTRARIAN', risk='REJECT',
    research_summary="Heavily shorted (6.4% of float, up from 3.8%) on an active 'AI makes call-centers uninvestable' thesis; CEO replaced over it.",
    risk_reason="Institutional STAND DOWN with a documented structural (non-transient) reason, plus sub-threshold breakout volume (1.44x)."),
'BP.L': dict(strategy_type='POSITION', alt=53, inst=62, align='CAUTIOUS', risk='APPROVE',
    research_summary="Saudi East-West pipeline outage (Houthi strikes) has spiked oil; Goldman raised PT 660p->700p Buy; insider STRONG_CLUSTER buying.",
    risk_reason="Genuine macro tailwind confirmed independently; approved as the presumptive 2nd/final session Energy slot alongside DVN."),
'MKC': dict(strategy_type='TURNAROUND', alt=None, inst=45, align='CAUTIOUS', risk='CAUTION',
    research_summary="Mid-merger with Unilever Foods ($45B deal, completion mid-2027) -- not in alt_data.json.",
    risk_reason="Q3 earnings Oct 1 (~2 weeks out) inside any hold window; reduce to 50% or wait until after the report."),

'STJ.L': dict(strategy_type='TURNAROUND', alt=43, inst=45, align='CAUTIOUS', risk='REJECT',
    research_summary="Redress programme nearing completion + buyback offsets decelerating net inflows; RSI 24 deeply oversold at support.",
    risk_reason="R:R 1.05 fails RISK.md 1.5:1 minimum, no override for conviction."),
'CBOE': dict(strategy_type='SWING', alt=49, inst=40, align='CAUTIOUS', risk='REJECT',
    research_summary="Record options ADV/dividend hikes are bullish, but live price already ~5% through the stated entry (270.44 vs 284.5), below both MAs.",
    risk_reason="R:R 1.28 fails minimum; stop also breaches 5% swing cap; entry level invalidated intraday."),
'BMY': dict(strategy_type='SWING', alt=50, inst=55, align='CAUTIOUS', risk='APPROVE',
    research_summary="Multiple positive pipeline readouts (mezigdomide Ph3 hit, CAR-T 96% ORR) plus Healthcare sector relative strength.",
    risk_reason="All checks pass; R:R 1.59 marginal but acceptable, stop and sizing clean."),
'AMGN': dict(strategy_type='SWING', alt=50, inst=45, align='CAUTIOUS', risk='CAUTION',
    research_summary="HSBC downgraded to Hold and UK MHRA suspended Tavneos -- real negative catalysts alongside RSI-17.8 oversold bounce setup.",
    risk_reason="Stop 5.7% exceeds 5% swing cap; unresolved regulatory overhang not visible in technical/fundamental screen."),
'ICE': dict(strategy_type='POSITION', alt=48, inst=55, align='CAUTIOUS', risk='REJECT',
    research_summary="MarketAxess $6B acquisition + record trading volumes directly support the rate-hike/exchange-volume thesis; but sustained insider selling ($5.5M) conflicts.",
    risk_reason="R:R 1.04 fails minimum despite best technical/fundamental setup in batch."),

'NVDA': dict(strategy_type='SWING', alt=35, inst=35, align='CONTRARIAN', risk='REJECT',
    research_summary="Insiders sold $653M net (MSPR -98.6) while NVDA also weighs a $10B Anthropic-IPO investment, a circular-financing move that deepened chip-sector selling after Amodei's own 'slow AI development' warning.",
    risk_reason="R:R technically clears (1.52) but insider selling + sector-confirmed Kindleberger Stage-4 bear market directly reinforce, not contradict, the macro short-bias thesis. CYCLE OVERRIDE also blocked POSITION classification, capping at SWING."),
'FIS': dict(strategy_type='SWING', alt=None, inst=45, align='CAUTIOUS', risk='CAUTION',
    research_summary="Positive core-banking momentum (new $100B client, 5 de novo charters) but stock whipsawed +5%/-2.2% in 48h and a live scan re-run downgraded the setup to Low conviction/neutral.",
    risk_reason="R:R clears (1.62) and no hard rule broken, but pullback structure needs reconfirmation before entry."),
'PBF': dict(strategy_type='SWING', alt=None, inst=50, align='CAUTIOUS', risk='REJECT',
    research_summary="Morgan Stanley PT raised to $76 (from $38) and strong refining tailwinds, but price already ran to $74.72 (+6.1% past stated $70.4 entry) on 3.3x volume.",
    risk_reason="R:R fails RISK.md minimum (1.45<1.5), and effective R:R at current live price is ~0.6:1 -- chasing risk."),
'BNR.DE': dict(strategy_type='SWING', alt=51, inst=45, align='CAUTIOUS', risk='REJECT',
    research_summary="Quiet, stable name with positive/rising news sentiment (0.464) and no negative catalysts.",
    risk_reason="R:R fails badly (0.98<1.5) -- simple hard-rule violation."),
'EQT': dict(strategy_type='SWING', alt=43, inst=50, align='CAUTIOUS', risk='REJECT',
    research_summary="Genuine Energy-sector tailwind (XLE +7.98%/1m) but mixed analyst PT cuts and rising short interest (+12.2% MoM, MSPR -29.6).",
    risk_reason="R:R fails badly (1.08<1.5); also competes with PBF for the last available Energy slot (DVN holds the other)."),
'BZU.MI': dict(strategy_type='SWING', alt=46, inst=40, align='CAUTIOUS', risk='CAUTION',
    research_summary="Strongly positive news sentiment (0.771) and value profile (P/E ~8.9), but EU Construction/cement sector proxies show weak relative momentum (-5% to -9%/1m).",
    risk_reason="R:R clears (1.71), no hard violation, but sector-relative headwind found independently warrants standard/reduced sizing."),
}

final_verdicts = {
    'WKL.AS': {'final_verdict': 'BUY', 'final_verdict_reason': 'Volume-confirmed breakout plus a below-market buyback; sole surviving Industrials candidate this session after sector-cap reconciliation across all 6 batches.'},
    'BP.L': {'final_verdict': 'BUY — REDUCED', 'final_verdict_reason': 'Strongest multi-signal case of the three APPROVEs (insider cluster, analyst upgrades, live oil-supply shock), but sized to 75% for correlated Energy exposure alongside existing DVN position and commodity-reversal risk in the thesis.'},
    'BMY': {'final_verdict': 'BUY — REDUCED', 'final_verdict_reason': 'Real pipeline catalysts, but sized to 60% because the Camzyos FDA decision (~Sep 30) sits inside the hold window on a thin R:R/tight stop with no alt-data or institutional confirmation.'},
}

candidates = []
for ticker, r in pop.items():
    res = research[ticker]
    fv = final_verdicts.get(ticker, {'final_verdict': None, 'final_verdict_reason': None})
    candidates.append({
        "ticker": ticker,
        "conviction": r['tech'],
        "setup": r['setup'],
        "entry": r['entry'],
        "stop": r['stop'],
        "target": r['target'],
        "rr_planned": r['rr'],
        "f_score": r['f_score'],
        "rating": r['rating'],
        "sector": r['sector'],
        "strategy_type": res['strategy_type'],
        "alt_data_score": res['alt'],
        "institutional_score": res['inst'],
        "institutional_alignment": res['align'],
        "risk_manager_verdict": res['risk'],
        "final_verdict": fv['final_verdict'],
        "final_verdict_reason": fv['final_verdict_reason'],
        "research_summary": res['research_summary'] + " RISK: " + res['risk_reason'],
    })

out = {"scan_date": "2026-09-16", "candidates": candidates}
json.dump(out, open('data/scan_test_group.json', 'w'), indent=2)
print("wrote", len(candidates), "candidates")
